[2024-05-07 15:57:20,453] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: update_visualization.run_spark scheduled__2024-05-06T02:00:00+00:00 [queued]>
[2024-05-07 15:57:22,267] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: update_visualization.run_spark scheduled__2024-05-06T02:00:00+00:00 [queued]>
[2024-05-07 15:57:22,304] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-05-07 15:57:22,310] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-05-07 15:57:22,311] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-05-07 15:57:23,649] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_spark> on 2024-05-06 02:00:00+00:00
[2024-05-07 15:57:23,822] {standard_task_runner.py:52} INFO - Started process 3168 to run task
[2024-05-07 15:57:23,989] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'update_visualization', 'run_spark', 'scheduled__2024-05-06T02:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/UpdateVisualization.py', '--cfg-path', '/tmp/tmpj7lw2vq3', '--error-file', '/tmp/tmpisjob5a_']
[2024-05-07 15:57:24,261] {standard_task_runner.py:80} INFO - Job 16: Subtask run_spark
[2024-05-07 15:57:25,354] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-07 15:57:28,516] {task_command.py:369} INFO - Running <TaskInstance: update_visualization.run_spark scheduled__2024-05-06T02:00:00+00:00 [running]> on host b29e3e3252f3
[2024-05-07 15:57:33,694] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=update_visualization
AIRFLOW_CTX_TASK_ID=run_spark
AIRFLOW_CTX_EXECUTION_DATE=2024-05-06T02:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-06T02:00:00+00:00
[2024-05-07 15:57:33,788] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-05-07 15:57:33,798] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python ../../spark.py']
[2024-05-07 15:57:33,984] {subprocess.py:85} INFO - Output:
[2024-05-07 15:57:34,951] {subprocess.py:92} INFO - python: can't open file '../../spark.py': [Errno 2] No such file or directory
[2024-05-07 15:57:34,995] {subprocess.py:96} INFO - Command exited with return code 2
[2024-05-07 15:57:35,383] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-05-07 15:57:35,458] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=update_visualization, task_id=run_spark, execution_date=20240506T020000, start_date=20240507T155720, end_date=20240507T155735
[2024-05-07 15:57:35,689] {standard_task_runner.py:97} ERROR - Failed to execute job 16 for task run_spark (Bash command failed. The command returned a non-zero exit code 2.; 3168)
[2024-05-07 15:57:35,809] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-05-07 15:57:36,519] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
