[2024-05-07 15:56:51,709] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: update_visualization.run_spark manual__2024-05-07T15:56:42.543603+00:00 [queued]>
[2024-05-07 15:56:52,529] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: update_visualization.run_spark manual__2024-05-07T15:56:42.543603+00:00 [queued]>
[2024-05-07 15:56:52,552] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-05-07 15:56:52,553] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-05-07 15:56:52,556] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-05-07 15:56:53,500] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_spark> on 2024-05-07 15:56:42.543603+00:00
[2024-05-07 15:56:53,630] {standard_task_runner.py:52} INFO - Started process 3140 to run task
[2024-05-07 15:56:54,321] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'update_visualization', 'run_spark', 'manual__2024-05-07T15:56:42.543603+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/UpdateVisualization.py', '--cfg-path', '/tmp/tmp0l5550ex', '--error-file', '/tmp/tmpgluxd6rw']
[2024-05-07 15:56:54,451] {standard_task_runner.py:80} INFO - Job 10: Subtask run_spark
[2024-05-07 15:56:57,154] {task_command.py:369} INFO - Running <TaskInstance: update_visualization.run_spark manual__2024-05-07T15:56:42.543603+00:00 [running]> on host b29e3e3252f3
[2024-05-07 15:57:01,678] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=update_visualization
AIRFLOW_CTX_TASK_ID=run_spark
AIRFLOW_CTX_EXECUTION_DATE=2024-05-07T15:56:42.543603+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-07T15:56:42.543603+00:00
[2024-05-07 15:57:01,825] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-05-07 15:57:01,983] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python ../../spark.py']
[2024-05-07 15:57:02,791] {subprocess.py:85} INFO - Output:
[2024-05-07 15:57:07,591] {subprocess.py:92} INFO - python: can't open file '../../spark.py': [Errno 2] No such file or directory
[2024-05-07 15:57:07,847] {subprocess.py:96} INFO - Command exited with return code 2
[2024-05-07 15:57:08,769] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-05-07 15:57:09,508] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=update_visualization, task_id=run_spark, execution_date=20240507T155642, start_date=20240507T155651, end_date=20240507T155709
[2024-05-07 15:57:11,265] {standard_task_runner.py:97} ERROR - Failed to execute job 10 for task run_spark (Bash command failed. The command returned a non-zero exit code 2.; 3140)
[2024-05-07 15:57:14,449] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-05-07 15:57:17,771] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
