[2024-05-07 16:06:18,482] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: update_visualization.run_spark manual__2024-05-07T16:06:16.294411+00:00 [queued]>
[2024-05-07 16:06:18,489] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: update_visualization.run_spark manual__2024-05-07T16:06:16.294411+00:00 [queued]>
[2024-05-07 16:06:18,489] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-05-07 16:06:18,490] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-05-07 16:06:18,490] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-05-07 16:06:18,507] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_spark> on 2024-05-07 16:06:16.294411+00:00
[2024-05-07 16:06:18,510] {standard_task_runner.py:52} INFO - Started process 3904 to run task
[2024-05-07 16:06:18,517] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'update_visualization', 'run_spark', 'manual__2024-05-07T16:06:16.294411+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/UpdateVisualization.py', '--cfg-path', '/tmp/tmpp2tnwgop', '--error-file', '/tmp/tmpv6sdbv3n']
[2024-05-07 16:06:18,520] {standard_task_runner.py:80} INFO - Job 169: Subtask run_spark
[2024-05-07 16:06:18,580] {task_command.py:369} INFO - Running <TaskInstance: update_visualization.run_spark manual__2024-05-07T16:06:16.294411+00:00 [running]> on host b29e3e3252f3
[2024-05-07 16:06:18,666] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=update_visualization
AIRFLOW_CTX_TASK_ID=run_spark
AIRFLOW_CTX_EXECUTION_DATE=2024-05-07T16:06:16.294411+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-07T16:06:16.294411+00:00
[2024-05-07 16:06:18,670] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-05-07 16:06:18,671] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python ../../spark.py']
[2024-05-07 16:06:18,690] {subprocess.py:85} INFO - Output:
[2024-05-07 16:06:18,806] {subprocess.py:92} INFO - python: can't open file '../../spark.py': [Errno 2] No such file or directory
[2024-05-07 16:06:18,810] {subprocess.py:96} INFO - Command exited with return code 2
[2024-05-07 16:06:18,830] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-05-07 16:06:18,833] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=update_visualization, task_id=run_spark, execution_date=20240507T160616, start_date=20240507T160618, end_date=20240507T160618
[2024-05-07 16:06:18,845] {standard_task_runner.py:97} ERROR - Failed to execute job 169 for task run_spark (Bash command failed. The command returned a non-zero exit code 2.; 3904)
[2024-05-07 16:06:18,859] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-05-07 16:06:18,897] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
