[2024-05-07 15:58:18,706] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: update_visualization.run_spark scheduled__2024-05-06T09:00:00+00:00 [queued]>
[2024-05-07 15:58:18,792] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: update_visualization.run_spark scheduled__2024-05-06T09:00:00+00:00 [queued]>
[2024-05-07 15:58:18,793] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-05-07 15:58:18,793] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-05-07 15:58:18,797] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-05-07 15:58:18,878] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_spark> on 2024-05-06 09:00:00+00:00
[2024-05-07 15:58:18,902] {standard_task_runner.py:52} INFO - Started process 3268 to run task
[2024-05-07 15:58:18,965] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'update_visualization', 'run_spark', 'scheduled__2024-05-06T09:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/UpdateVisualization.py', '--cfg-path', '/tmp/tmpjv3gjpos', '--error-file', '/tmp/tmp2kapydz6']
[2024-05-07 15:58:18,972] {standard_task_runner.py:80} INFO - Job 44: Subtask run_spark
[2024-05-07 15:58:19,167] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-07 15:58:19,339] {task_command.py:369} INFO - Running <TaskInstance: update_visualization.run_spark scheduled__2024-05-06T09:00:00+00:00 [running]> on host b29e3e3252f3
[2024-05-07 15:58:19,726] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=update_visualization
AIRFLOW_CTX_TASK_ID=run_spark
AIRFLOW_CTX_EXECUTION_DATE=2024-05-06T09:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-06T09:00:00+00:00
[2024-05-07 15:58:19,730] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-05-07 15:58:19,732] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python ../../spark.py']
[2024-05-07 15:58:19,783] {subprocess.py:85} INFO - Output:
[2024-05-07 15:58:19,962] {subprocess.py:92} INFO - python: can't open file '../../spark.py': [Errno 2] No such file or directory
[2024-05-07 15:58:19,965] {subprocess.py:96} INFO - Command exited with return code 2
[2024-05-07 15:58:20,025] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-05-07 15:58:20,036] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=update_visualization, task_id=run_spark, execution_date=20240506T090000, start_date=20240507T155818, end_date=20240507T155820
[2024-05-07 15:58:20,080] {standard_task_runner.py:97} ERROR - Failed to execute job 44 for task run_spark (Bash command failed. The command returned a non-zero exit code 2.; 3268)
[2024-05-07 15:58:20,135] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-05-07 15:58:20,280] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
