[2024-05-07 15:58:42,805] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: update_visualization.run_spark scheduled__2024-05-06T15:00:00+00:00 [queued]>
[2024-05-07 15:58:42,822] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: update_visualization.run_spark scheduled__2024-05-06T15:00:00+00:00 [queued]>
[2024-05-07 15:58:42,822] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-05-07 15:58:42,823] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-05-07 15:58:42,823] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-05-07 15:58:42,848] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_spark> on 2024-05-06 15:00:00+00:00
[2024-05-07 15:58:42,856] {standard_task_runner.py:52} INFO - Started process 3359 to run task
[2024-05-07 15:58:42,860] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'update_visualization', 'run_spark', 'scheduled__2024-05-06T15:00:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/UpdateVisualization.py', '--cfg-path', '/tmp/tmp8nx0p6ye', '--error-file', '/tmp/tmpd5ixkdi2']
[2024-05-07 15:58:42,863] {standard_task_runner.py:80} INFO - Job 68: Subtask run_spark
[2024-05-07 15:58:42,941] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-07 15:58:43,048] {task_command.py:369} INFO - Running <TaskInstance: update_visualization.run_spark scheduled__2024-05-06T15:00:00+00:00 [running]> on host b29e3e3252f3
[2024-05-07 15:58:43,253] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=update_visualization
AIRFLOW_CTX_TASK_ID=run_spark
AIRFLOW_CTX_EXECUTION_DATE=2024-05-06T15:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-06T15:00:00+00:00
[2024-05-07 15:58:43,257] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-05-07 15:58:43,259] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python ../../spark.py']
[2024-05-07 15:58:43,277] {subprocess.py:85} INFO - Output:
[2024-05-07 15:58:43,543] {subprocess.py:92} INFO - python: can't open file '../../spark.py': [Errno 2] No such file or directory
[2024-05-07 15:58:43,551] {subprocess.py:96} INFO - Command exited with return code 2
[2024-05-07 15:58:43,634] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-05-07 15:58:43,647] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=update_visualization, task_id=run_spark, execution_date=20240506T150000, start_date=20240507T155842, end_date=20240507T155843
[2024-05-07 15:58:43,682] {standard_task_runner.py:97} ERROR - Failed to execute job 68 for task run_spark (Bash command failed. The command returned a non-zero exit code 2.; 3359)
[2024-05-07 15:58:43,726] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-05-07 15:58:43,922] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
