[2024-05-07 15:59:52,263] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: update_visualization.run_spark scheduled__2024-05-07T14:15:00+00:00 [queued]>
[2024-05-07 15:59:52,286] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: update_visualization.run_spark scheduled__2024-05-07T14:15:00+00:00 [queued]>
[2024-05-07 15:59:52,286] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-05-07 15:59:52,286] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-05-07 15:59:52,287] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-05-07 15:59:52,308] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_spark> on 2024-05-07 14:15:00+00:00
[2024-05-07 15:59:52,323] {standard_task_runner.py:52} INFO - Started process 3668 to run task
[2024-05-07 15:59:52,329] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'update_visualization', 'run_spark', 'scheduled__2024-05-07T14:15:00+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/UpdateVisualization.py', '--cfg-path', '/tmp/tmpicrymbh4', '--error-file', '/tmp/tmp00dbj9on']
[2024-05-07 15:59:52,331] {standard_task_runner.py:80} INFO - Job 161: Subtask run_spark
[2024-05-07 15:59:52,373] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-07 15:59:52,443] {task_command.py:369} INFO - Running <TaskInstance: update_visualization.run_spark scheduled__2024-05-07T14:15:00+00:00 [running]> on host b29e3e3252f3
[2024-05-07 15:59:52,568] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=update_visualization
AIRFLOW_CTX_TASK_ID=run_spark
AIRFLOW_CTX_EXECUTION_DATE=2024-05-07T14:15:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-07T14:15:00+00:00
[2024-05-07 15:59:52,573] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-05-07 15:59:52,575] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python ../../spark.py']
[2024-05-07 15:59:52,602] {subprocess.py:85} INFO - Output:
[2024-05-07 15:59:52,728] {subprocess.py:92} INFO - python: can't open file '../../spark.py': [Errno 2] No such file or directory
[2024-05-07 15:59:52,728] {subprocess.py:96} INFO - Command exited with return code 2
[2024-05-07 15:59:52,853] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-05-07 15:59:52,866] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=update_visualization, task_id=run_spark, execution_date=20240507T141500, start_date=20240507T155952, end_date=20240507T155952
[2024-05-07 15:59:52,920] {standard_task_runner.py:97} ERROR - Failed to execute job 161 for task run_spark (Bash command failed. The command returned a non-zero exit code 2.; 3668)
[2024-05-07 15:59:52,967] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-05-07 15:59:53,064] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
