[2024-05-07 15:56:55,607] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: update_visualization.run_spark scheduled__2024-05-06T00:45:00+00:00 [queued]>
[2024-05-07 15:56:55,814] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: update_visualization.run_spark scheduled__2024-05-06T00:45:00+00:00 [queued]>
[2024-05-07 15:56:55,828] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-05-07 15:56:55,850] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-05-07 15:56:55,851] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-05-07 15:56:56,276] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_spark> on 2024-05-06 00:45:00+00:00
[2024-05-07 15:56:56,483] {standard_task_runner.py:52} INFO - Started process 3144 to run task
[2024-05-07 15:56:56,685] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'update_visualization', 'run_spark', 'scheduled__2024-05-06T00:45:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/UpdateVisualization.py', '--cfg-path', '/tmp/tmpjdf8k0su', '--error-file', '/tmp/tmpq6gab9gx']
[2024-05-07 15:56:56,721] {standard_task_runner.py:80} INFO - Job 11: Subtask run_spark
[2024-05-07 15:56:57,690] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-07 15:56:59,379] {task_command.py:369} INFO - Running <TaskInstance: update_visualization.run_spark scheduled__2024-05-06T00:45:00+00:00 [running]> on host b29e3e3252f3
[2024-05-07 15:57:04,554] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=update_visualization
AIRFLOW_CTX_TASK_ID=run_spark
AIRFLOW_CTX_EXECUTION_DATE=2024-05-06T00:45:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-06T00:45:00+00:00
[2024-05-07 15:57:04,660] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-05-07 15:57:04,754] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python ../../spark.py']
[2024-05-07 15:57:05,589] {subprocess.py:85} INFO - Output:
[2024-05-07 15:57:07,570] {subprocess.py:92} INFO - python: can't open file '../../spark.py': [Errno 2] No such file or directory
[2024-05-07 15:57:07,700] {subprocess.py:96} INFO - Command exited with return code 2
[2024-05-07 15:57:10,013] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-05-07 15:57:10,186] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=update_visualization, task_id=run_spark, execution_date=20240506T004500, start_date=20240507T155655, end_date=20240507T155710
[2024-05-07 15:57:11,105] {standard_task_runner.py:97} ERROR - Failed to execute job 11 for task run_spark (Bash command failed. The command returned a non-zero exit code 2.; 3144)
[2024-05-07 15:57:12,008] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-05-07 15:57:17,131] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
